### ISSUE TITLE
groupTitle - color in dark mode

### ISSUE THREAD

**Issue by polaksta** [liodali/checkbox_grouped#26]
In dark mode, the 'groupTitle'  (SimpleGroupedCheckbox) is displayed in black instead of white — this can cause a readability problem.

![zrzut](https://user-images.githubusercontent.com/25083571/101987009-c4866a80-3c91-11eb-86ff-86ec8580dfff.jpg)

Oops. By the way, it turned out that I made a typo in my application - it should be 'Heat' instead of 'Hear' ;-)

**Comment by liodali** [comment]
ok i will add style for title grouped it will be add in next version
