### ISSUE TITLE
Update The ui after change selected items in GroupController

### ISSUE THREAD

**Issue by NubianCode** [liodali/checkbox_grouped#47]
When change selected items in controller by initSelectedItem method and reload the UI by setState method no
 thing change in the ui but its chnage in the list of GroupController

the code
![Capture](https://user-images.githubusercontent.com/85127721/123442975-bc5e9e80-d5d5-11eb-9ddd-fdb7edb4d79f.PNG)

**Comment by NubianCode** [comment]
another issue :
when i select all the checksbox by enter the values of the all items in initSelectedItem, it's change the icon of helper to '-' insted instead of check icon 
![Uploading Capture.PNG…]()

**Comment by liodali** [comment]
ok i will see the problem and i will fix it soon
but can you provide me more information all widget that you are working on to understand use case

**Comment by NubianCode** [comment]
i have checked your code and i have found the issue, the issue is you init the values of SimpleGroupedCheckbox int he overwritten method initState, the method init state called one time, it's cold before create the page, after the page is created it's will never called again, that mean the values will be never chagae by setState, you shoud update the values also in bulid function.
![Capture](https://user-images.githubusercontent.com/85127721/123495039-46345900-d622-11eb-90de-72a7c77bb5a8.PNG)

**Comment by NubianCode** [comment]
انت عربي يا الحبيب، اهلا و سهلا بيك، يا صديقي المشكلة انك تقوم بإسنادا  القيم للمتغيرات في الدالة ست إستيت التي يتم نداها مرة واحدة قبل ان يتم صنع الواجهه، بعد عرض الوجهه لم يتم إسناد القيمة الجديدة للمتغيرات لان دالة ست إستيت لن تنادى مره اخرى

**Comment by NubianCode** [comment]
جرب هذا الكود:

```
bool selectFrist = true;

TextButton(
            child : Text("unslect first checbox"),
            onPressed: () {sekectFrust = !selectFirst,  setState(() {})),
            child: const Text('Enabled'),
          ),
SimpleGroupedCheckbox<int>(
                    controller: controller,
                    itemsTitle: ["1" ,"2","4","5"],
                    values: [1,2,4,5],
                    activeColor: Colors.red,
                    checkFirstElement: selectFrist ,
                    multiSelection: false,
                  )

```

**Comment by liodali** [comment]
you want to change values selection programmatically by re-set them in controller that what you want to do ?

**Comment by NubianCode** [comment]
because i have a lot of checkbox groups i want to make a checkbox to select all the groups and un select all of them like what helper do

**Comment by liodali** [comment]
I will add that feature by the end of next week 
i will add new method in controller to re-set items

**Comment by NubianCode** [comment]
another thing, when you init all items by the constructor of  GroupController by var initSelectedItem it's will be all selected but the icon in the checkbox of helper show mince icons instead of check icon, look at the image
![Uploading Capture.PNG…]()

**Comment by NubianCode** [comment]
another thing, when you init all items by the constructor of GroupController by var initSelectedItem it's will be all selected but the icon in the checkbox of helper show mince icons instead of check icon, look at the image
![Capture](https://user-images.githubusercontent.com/85127721/123507022-794d0b80-d667-11eb-90cb-ae4ac33d0976.PNG)

**Comment by liodali** [comment]
ok i will fix also that bug

**Comment by NubianCode** [comment]
هل يمكننا التواصل على فيسبوك، ليس لدي حساب تويتر

**Comment by liodali** [comment]
I prefer to use another platform if you don't have any problems with that
you can reach me on skype : lionel.dali

**Comment by NubianCode** [comment]
ok

**Comment by liodali** [comment]
check the new version  `1.4.1`
